- hosts: nginx
  become: true
  tasks:
  - name: "Install NGINX"
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: "Start NGINX"
    service:
      name: nginx
      state: started
  - name: "Update packages"
    apt:
      update_cache: "yes"
      force_apt_get: "yes"